# netlify.yml
version: 1.0
build:
  base: ./
  command: npm run build
  publish: dist/
  environment:
    NODE_VERSION: 18
    NPM_VERSION: 9

plugins:
  - package: netlify-plugin-cache
    config:
      paths:
        - node_modules/.cache
        - .eslintcache

headers:
  - path: /*
    headers:
      - key: X-Frame-Options
        value: DENY
      - key: X-XSS-Protection
        value: 1; mode=block
      - key: X-Content-Type-Options
        value: nosniff
      - key: Referrer-Policy
        value: no-referrer-when-downgrade

  - path: /assets/*
    headers:
      - key: Cache-Control
        value: public, max-age=31536000, immutable

redirects:
  - from: /*
    to: /index.html
    status: 200
    force: true