# netlify.toml
[build]
  command = "npm run build"
  publish = "dist"
  environment = { 
    NODE_VERSION = "18",
    SECRETS_SCAN_ENABLED = "false"
  }

# Redirects and rewrites
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

# Asset handling
[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200

# Headers for security and caching
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer-when-downgrade"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"